apiVersion: v1
kind: Secret
metadata:
  name: mcp-jira-secret
  namespace: default
  labels:
    app: mcp-jira-server
    component: mcp-server
type: Opaque
stringData:
  # IMPORTANT: Replace these with your actual Jira credentials
  # In production, use external secrets management (Vault, Sealed Secrets, etc.)
  JIRA_URL: "https://your-domain.atlassian.net"
  JIRA_USER_EMAIL: "your-email@example.com"
  JIRA_API_TOKEN: "your-jira-api-token-here"

  # Optional: OAuth credentials
  # JIRA_OAUTH_CLIENT_ID: ""
  # JIRA_OAUTH_CLIENT_SECRET: ""
---
# Example: How to create this secret from command line
# kubectl create secret generic mcp-jira-secret \
#   --from-literal=JIRA_URL=https://your-domain.atlassian.net \
#   --from-literal=JIRA_USER_EMAIL=your-email@example.com \
#   --from-literal=JIRA_API_TOKEN=your-api-token \
#   --namespace=default
