---
# App of Apps Pattern
# Root application that manages all other applications

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JohnYoungSuh/suhlabs.git
    targetRevision: HEAD
    path: cluster/gitops/argo-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
