---
apiVersion: v1
kind: Namespace
metadata:
  name: aiops

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: aiops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: aiops
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
        - name: ollama
          image: ollama/ollama:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 11434
              name: http
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0:11434"
            - name: OLLAMA_MODELS
              value: "/root/.ollama/models"
          volumeMounts:
            - name: ollama-models
              mountPath: /root/.ollama
          resources:
            requests:
              cpu: 2000m
              memory: 8Gi
            limits:
              cpu: 4000m
              memory: 16Gi
          livenessProbe:
            httpGet:
              path: /
              port: 11434
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 11434
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: ollama-models
          persistentVolumeClaim:
            claimName: ollama-models

---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: aiops
  labels:
    app: ollama
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 11434
      targetPort: 11434
  selector:
    app: ollama

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-pull-llama3
  namespace: aiops
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: pull-model
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for Ollama to be ready..."
              until curl -f http://ollama:11434/; do
                sleep 5
              done
              echo "Pulling llama3.1:8b model..."
              curl -X POST http://ollama:11434/api/pull -d '{"name":"llama3.1:8b"}'
