# values-loki.yaml (grafana/loki-stack)

loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: "longhorn"

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101

grafana:
  enabled: false # We use the Grafana from kube-prometheus-stack instead
