---
# FreeIPA CA ClusterIssuer
# Uses internal FreeIPA Certificate Authority for service-to-service TLS
# Certificates NOT trusted by browsers (requires manual CA cert installation)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: freeipa-ca
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cluster-issuer
spec:
  ca:
    # Secret containing FreeIPA CA certificate and private key
    # This secret will be created by Ansible from FreeIPA server
    secretName: freeipa-ca-key-pair

---
# Secret template for FreeIPA CA key pair
# This will be populated by Ansible playbook from FreeIPA server:
# - Fetch /etc/ipa/ca.crt from FreeIPA server
# - Fetch /etc/ipa/private/ca.key from FreeIPA server (if accessible)
# - Create secret with tls.crt and tls.key
#
# Note: If FreeIPA CA private key is not accessible (HSM-backed),
# use cert-manager's CA injector with a separate signing certificate
apiVersion: v1
kind: Secret
metadata:
  name: freeipa-ca-key-pair
  namespace: cert-manager
type: kubernetes.io/tls
data:
  # These will be base64-encoded by Ansible
  tls.crt: LS0tLS1... # FreeIPA CA certificate (PEM format)
  tls.key: LS0tLS1... # FreeIPA CA private key (PEM format)
# stringData:
#   tls.crt: |
#     -----BEGIN CERTIFICATE-----
#     [FreeIPA CA certificate content]
#     -----END CERTIFICATE-----
#   tls.key: |
#     -----BEGIN PRIVATE KEY-----
#     [FreeIPA CA private key content]
#     -----END PRIVATE KEY-----
