apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-ops-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/suhlabs/aiops-substrate.git'
    path: cluster
    targetRevision: HEAD
    directory:
      recurse: true
      exclude: '**/foundation/vault/.vault-keys*.json' # Do not allow Argo to sync local dev keys
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
